/**
 * Internal dependencies
 */
import { DatePattern } from './types';

export const DATE_PATTERN_PRESETS: DatePattern[] = [
	{
		key: 'iso_datetime',
		regex: '(\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}(:\\d{2})?)',
		format: 'YYYY-MM-DD HH:mm:ss',
		label: 'ISO date with time',
		enabled: true,
		removable: false,
	},
	{
		key: 'iso_datetime_hhmm',
		regex: '(\\d{4}-\\d{2}-\\d{2}\\s+\\d{4})(?!\\d)',
		format: 'YYYY-MM-DD HHmm',
		label: 'ISO date with bare time',
		enabled: true,
		removable: false,
	},
	{
		key: 'iso_datetime_t',
		regex: '(\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}(:\\d{2})?)',
		format: 'YYYY-MM-DDTHH:mm:ss',
		label: 'ISO date T time',
		enabled: true,
		removable: false,
	},
	{
		key: 'iso_date',
		regex: '(\\d{4}-\\d{2}-\\d{2})',
		format: 'YYYY-MM-DD',
		label: 'ISO date',
		enabled: true,
		removable: false,
	},
	{
		key: 'eu_datetime',
		regex: '(\\d{2}\\.\\d{2}\\.\\d{4} \\d{2}:\\d{2})',
		format: 'DD.MM.YYYY HH:mm',
		label: 'EU date with time',
		enabled: true,
		removable: false,
	},
	{
		key: 'eu_date',
		regex: '(\\d{2}\\.\\d{2}\\.\\d{4})',
		format: 'DD.MM.YYYY',
		label: 'EU date',
		enabled: true,
		removable: false,
	},
	{
		key: 'eu_date_yy',
		regex: '(\\d{2}\\.\\d{2}\\.\\d{2})(?!\\d)',
		format: 'DD.MM.YY',
		label: 'EU date 2-digit year',
		enabled: true,
		removable: false,
	},
	{
		key: 'compact_datetime_hhmmss',
		regex: '(\\d{8}_\\d{6})',
		format: 'YYYYMMDD_HHmmss',
		label: 'Compact with time seconds',
		enabled: true,
		removable: false,
	},
	{
		key: 'compact_datetime_hhmm',
		regex: '(\\d{8}_\\d{4})',
		format: 'YYYYMMDD_HHmm',
		label: 'Compact with time minutes',
		enabled: true,
		removable: false,
	},
	{
		key: 'compact_datetime_dash',
		regex: '(\\d{8}-\\d{6})',
		format: 'YYYYMMDD-HHmmss',
		label: 'Compact dash time',
		enabled: true,
		removable: false,
	},
	{
		key: 'compact_date',
		regex: '((?:19|20)\\d{6})(?!\\d)',
		format: 'YYYYMMDD',
		label: 'Compact date',
		enabled: true,
		removable: false,
	},
	{
		key: 'compact_date_yy',
		regex: '(\\d{6})(?!\\d)',
		format: 'YYMMDD',
		label: 'Compact 2-digit year',
		enabled: true,
		removable: false,
	},
	{
		key: 'us_date',
		regex: '(\\d{1,2}-\\d{1,2}-\\d{4})',
		format: 'MM-DD-YYYY',
		label: 'US date',
		enabled: true,
		removable: false,
	},
	{
		key: 'military_dmy',
		regex: '(\\d{1,2}-[A-Z]{3}-\\d{4})',
		format: 'DD-MMM-YYYY',
		label: 'Military style',
		enabled: true,
		removable: false,
	},
	{
		key: 'german_dotted',
		regex: '(\\d{1,2}\\.\\s*[A-Za-zäöüß]{3,4}\\.?\\s*\\d{4})',
		format: 'DD. MMM. YYYY',
		label: 'German dotted',
		enabled: true,
		removable: false,
	},
	{
		key: 'german_full',
		regex: '(\\d{1,2}\\.\\s*[A-Za-zäöüß]{4,}\\.?\\s*\\d{4})',
		format: 'DD. MMMM YYYY',
		label: 'German full month',
		enabled: true,
		removable: false,
	},
	{
		key: 'english_text',
		regex: '([A-Z][a-z]{2,8}\\s+\\d{1,2},?\\s+\\d{4})',
		format: 'MMM DD, YYYY',
		label: 'English text',
		enabled: true,
		removable: false,
	},
	{
		key: 'german_compact',
		regex: '(\\d{1,2}\\.[A-Za-zäöüß]{3,4}\\.\\d{4})',
		format: 'DD.MMM.YYYY',
		label: 'German compact',
		enabled: true,
		removable: false,
	},
];
