// Copy of https://github.com/iamacup/react-native-markdown-display/blob/master/src/lib/data/textStyleProps.js
export default [
    'textShadowOffset',
    'color',
    'fontSize',
    'fontStyle',
    'fontWeight',
    'lineHeight',
    'textAlign',
    'textDecorationLine',
    'textShadowColor',
    'fontFamily',
    'textShadowRadius',
    'includeFontPadding',
    'textAlignVertical',
    'fontVariant',
    'letterSpacing',
    'textDecorationColor',
    'textDecorationStyle',
    'textTransform',
    'writingDirection',
  ];