import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync } from 'fs';
import { join, extname, basename } from 'path';
import { fileURLToPath } from 'url';
import { Readable } from 'stream';
import { createHash } from 'crypto';

const __filename = fileURLToPath(import.meta.url);
const __dirname = join(__filename, '..');

const PROJECT_ROOT = join(__dirname, '..', '..');
const ICONS_DIR = join(PROJECT_ROOT, 'src', 'assets', 'icons');
const OUTPUT_DIR = join(ICONS_DIR, 'build');
const GLYPHMAP_PATH = join(OUTPUT_DIR, 'glyphmap.json');
const TTF_PATH = join(OUTPUT_DIR, 'build-icons.ttf');
const SVG_FONT_PATH = join(OUTPUT_DIR, 'build-icons.svg');
const LINK_ASSETS_MANIFEST_PATH = join(PROJECT_ROOT, 'android', 'link-assets-manifest.json');
const ANDROID_FONTS_DIR = join(PROJECT_ROOT, 'android', 'app', 'src', 'main', 'assets', 'fonts');

const START_CODE = 0xe900;

interface IconEntry {
	name: string;
	filePath: string;
	svgContent: string;
}

export async function buildIcons(): Promise<void> {
	const args = process.argv.slice(2);
	const modeArg = args.find((a) => a.startsWith('--mode='));
	const mode = modeArg ? modeArg.split('=')[1] : 'regenerative';

	if (mode !== 'regenerative' && mode !== 'additive') {
		throw new Error(`Unknown mode: "${mode}". Must be "regenerative" or "additive".`);
	}

	const isAdditive = mode === 'additive';

	const previousGlyphmap = existsSync(GLYPHMAP_PATH)
		? JSON.parse(readFileSync(GLYPHMAP_PATH, 'utf-8'))
		: {};

	if (isAdditive && Object.keys(previousGlyphmap).length === 0) {
		throw new Error(
			'Additive mode requires an existing glyphmap.json. ' +
				'Run without --mode=additive first to generate the initial set.'
		);
	}

	console.log(`Mode: ${mode}`);
	console.log(`Source SVGs directory: ${ICONS_DIR}`);
	console.log(`Output directory: ${OUTPUT_DIR}`);

	const iconEntries = loadAndCleanSVGs();

	if (iconEntries.length === 0) {
		throw new Error(`No SVG files found in ${ICONS_DIR}`);
	}

	if (isAdditive) {
		const prevNames = new Set(Object.keys(previousGlyphmap));
		const currentNames = new Set(iconEntries.map((e) => e.name));
		const removedNames = [...prevNames].filter((n) => !currentNames.has(n));
		if (removedNames.length > 0) {
			throw new Error(
				`Additive mode: the following icons are in glyphmap.json but have no source SVG: ` +
					`${removedNames.join(', ')}. ` +
					`Use regenerative mode to drop them.`
			);
		}
	}

	const glyphmap = assignCodes(iconEntries, previousGlyphmap);

	console.log(`Icons found: ${iconEntries.length}`);
	for (const icon of iconEntries) {
		const code = glyphmap[icon.name];
		const hex = code.toString(16);
		console.log(`  ${icon.name} -> U+${hex} (${code})`);
	}

	await generateFont(iconEntries, glyphmap);

	mkdirSync(OUTPUT_DIR, { recursive: true });
	writeFileSync(GLYPHMAP_PATH, JSON.stringify(glyphmap, null, '\t') + '\n');
	console.log(`Wrote ${GLYPHMAP_PATH}`);

	const readmePath = join(OUTPUT_DIR, 'README.md');
	writeFileSync(
		readmePath,
		`# Build Icons

This directory is a **build artifact** generated by \`yarn buildIcons\`.
Do not manually edit files in this directory.

To add or update icons, place \`.svg\` files in \`src/assets/icons/\` and run:

\`\`\`
yarn buildIcons
\`\`\`

Generated at: ${new Date().toISOString()}
`,
		'utf-8'
	);
	console.log(`Wrote ${readmePath}`);

	updateLinkAssetsManifest();
	copyFontToNativeAssets();

	console.log('Done.');
}

function stripHiddenGroups(svgString: string): string {
	const { DOMParser } = require('@xmldom/xmldom');

	const doc = new DOMParser().parseFromString(svgString, 'image/svg+xml');

	function isHidden(el: any): boolean {
		if (!el || el.nodeType !== 1) return false;
		const display = (el.getAttribute('display') || '').toLowerCase();
		const style = (el.getAttribute('style') || '').toLowerCase();
		const fill = (el.getAttribute('fill') || '').toLowerCase();

		if (display === 'none' || style.includes('display:none') || fill === 'none') {
			return true;
		}

		return false;
	}

	function pruneHidden(el: any, parentHidden: boolean): boolean {
		if (!el || !el.childNodes) return false;

		const toRemove: number[] = [];
		let childHidden: boolean[] = [];

		for (let i = 0; i < el.childNodes.length; i++) {
			const child = el.childNodes[i];
			if (child.nodeType !== 1) continue;

			const hidden = parentHidden || isHidden(child);
			childHidden[i] = hidden;

			if (hidden) {
				toRemove.push(i);
			} else {
				pruneHidden(child, hidden);
			}
		}

		let removed = 0;
		for (const idx of toRemove) {
			el.removeChild(el.childNodes[idx - removed]);
			removed++;
		}

		return removed > 0;
	}

	pruneHidden(doc.documentElement, false);

	return doc.toString();
}

function loadAndCleanSVGs(): IconEntry[] {
	const { optimize } = require('svgo');

	const entries: IconEntry[] = [];
	const files = readdirSync(ICONS_DIR);

	for (const file of files.sort()) {
		if (extname(file).toLowerCase() !== '.svg') continue;

		const filePath = join(ICONS_DIR, file);
		const rawSvg = readFileSync(filePath, 'utf-8');
		const name = basename(file, '.svg');

		if (!/^[a-z0-9_]+$/.test(name)) {
			console.warn(
				`  Notice: icon "${name}" does not follow the underscore convention (use lowercase letters, digits, and underscores only).`
			);
		}

		const prunedSvg = rawSvg
			.replace(/<path\b[^>]*\bfill\s*=\s*['"]none['"][^>]*\/>/gi, '')
			.replace(
				/<(?:path|g|rect|circle|ellipse|polygon|polyline|line)\b[^>]*\bdisplay\s*=\s*['"]none['"][^>]*\/>/gi,
				''
			)
			.replace(
				/<(?:path|g|rect|circle|ellipse|polygon|polyline|line)\b[^>]*\bopacity\s*=\s*['"]0['"][^>]*\/>/gi,
				''
			);

		const cleanedSvg = stripHiddenGroups(prunedSvg);

		const result = optimize(cleanedSvg, {
			multipass: true,
			plugins: [
				'removeDoctype',
				'removeXMLProcInst',
				'removeComments',
				'removeMetadata',
				'removeEditorsNSData',
				'removeStyleElement',
				'removeScripts',
				'convertShapeToPath',
				'removeDimensions',
				{
					name: 'removeAttrs',
					params: {
						attrs: '(fill|stroke|fill-opacity|stroke-opacity|class)',
					},
				},
			],
		});

		const pathCount = (result.data.match(/<path\b/gi) || []).length;
		const svgContent =
			pathCount > 1 ? result.data.replace('<svg ', '<svg fill-rule="evenodd" ') : result.data;

		entries.push({
			name,
			filePath,
			svgContent,
		});
	}

	return entries;
}

function assignCodes(
	entries: IconEntry[],
	previousGlyphmap: Record<string, number>
): Record<string, number> {
	const glyphmap: Record<string, number> = {};
	const usedCodes = new Set<number>();
	let nextCode = START_CODE;

	for (const [name, code] of Object.entries(previousGlyphmap)) {
		glyphmap[name] = code;
		usedCodes.add(code);
	}

	for (const code of usedCodes) {
		if (code >= nextCode) {
			nextCode = code + 1;
		}
	}

	for (const entry of entries) {
		if (glyphmap[entry.name] !== undefined) continue;

		while (usedCodes.has(nextCode)) {
			nextCode++;
		}
		glyphmap[entry.name] = nextCode;
		usedCodes.add(nextCode);
		nextCode++;
	}

	return glyphmap;
}

function generateFont(entries: IconEntry[], glyphmap: Record<string, number>): Promise<void> {
	return new Promise<void>((resolve, reject) => {
		const { SVGIcons2SVGFontStream } = require('svgicons2svgfont');
		const svg2ttf = require('svg2ttf');

		const fontStream = new SVGIcons2SVGFontStream({
			fontName: 'build-icons',
			fontHeight: 960,
			normalize: true,
			log: () => {},
		});

		mkdirSync(OUTPUT_DIR, { recursive: true });

		const chunks: Buffer[] = [];
		fontStream.on('data', (chunk: Buffer) => {
			chunks.push(Buffer.from(chunk));
		});

		fontStream.on('end', () => {
			try {
				let svgFontContent = Buffer.concat(chunks).toString('utf-8');

				svgFontContent = svgFontContent.replace(
					/<font-face\s+[^>]*\/>/g,
					(match: string) => {
						return match
							.replace(/ascent="[^"]*"/, 'ascent="960"')
							.replace(/descent="[^"]*"/, 'descent="-64"');
					}
				);

				writeFileSync(SVG_FONT_PATH, svgFontContent, 'utf-8');
				console.log(`Wrote ${SVG_FONT_PATH}`);

				const ttfResult = svg2ttf(svgFontContent, {
					copyright: '',
					description: 'Generated by buildIcons script',
				});
				const ttfBuffer = fixVerticalMetrics(ttfResult.buffer);
				writeFileSync(TTF_PATH, ttfBuffer);
				console.log(`Wrote ${TTF_PATH}`);

				resolve();
			} catch (err) {
				reject(err);
			}
		});

		fontStream.on('error', reject);

		for (const entry of entries) {
			const code = glyphmap[entry.name];
			const char = String.fromCharCode(code);
			const readable = Readable.from(Buffer.from(entry.svgContent, 'utf-8'));
			(readable as any).metadata = {
				unicode: [char],
				name: entry.name,
			};
			fontStream.write(readable);
		}

		fontStream.end();
	});
}

function fixVerticalMetrics(ttfBuffer: Buffer): Buffer {
	const buf = Buffer.from(ttfBuffer);
	const numTables = buf.readUInt16BE(4);

	for (let i = 0; i < numTables; i++) {
		const offset = 12 + i * 16;
		const tag = buf.toString('ascii', offset, offset + 4);
		if (tag === 'OS/2') {
			const tableOffset = buf.readUInt32BE(offset + 8);

			const typoAsc = buf.readInt16BE(tableOffset + 68);
			const typoDesc = buf.readInt16BE(tableOffset + 70);

			buf.writeUInt16BE(typoAsc, tableOffset + 74);
			buf.writeUInt16BE(Math.abs(typoDesc), tableOffset + 76);
			console.log(
				`  Fixed vertical metrics: usWinAscent=${typoAsc}, usWinDescent=${Math.abs(typoDesc)}`
			);
			break;
		}
	}

	return buf;
}

function sha1(filePath: string): string {
	const content = readFileSync(filePath);
	return createHash('sha1').update(content).digest('hex');
}

function updateLinkAssetsManifest(): void {
	if (!existsSync(LINK_ASSETS_MANIFEST_PATH)) {
		console.warn(`  Warning: ${LINK_ASSETS_MANIFEST_PATH} not found, skipping update.`);
		return;
	}

	const manifest = JSON.parse(readFileSync(LINK_ASSETS_MANIFEST_PATH, 'utf-8'));

	const newEntries = [
		{
			path: 'src/assets/icons/build/build-icons.svg',
			sha1: sha1(SVG_FONT_PATH),
		},
		{
			path: 'src/assets/icons/build/build-icons.ttf',
			sha1: sha1(TTF_PATH),
		},
	];

	manifest.data = manifest.data.filter(
		(entry: { path: string }) => !entry.path.startsWith('src/assets/icons/')
	);

	manifest.data.push(...newEntries);

	writeFileSync(LINK_ASSETS_MANIFEST_PATH, JSON.stringify(manifest, null, 2) + '\n');
	console.log(`Updated ${LINK_ASSETS_MANIFEST_PATH}`);
}

function copyFontToNativeAssets(): void {
	mkdirSync(ANDROID_FONTS_DIR, { recursive: true });
	copyFileSync(TTF_PATH, join(ANDROID_FONTS_DIR, 'build-icons.ttf'));
	console.log(`Copied build-icons.ttf to ${ANDROID_FONTS_DIR}`);
}
